vles:
  flair:
    pretrained_weights_root_path: '/home/olivieri/exp/data/private/huggingface/hub/flair'
    checkpoint_path: '/home/olivieri/exp/data/private/exps/vle/1-dM_vs_dT/250902_2047/weights/flair-flair-cc3m-recap.pt-text_proj_L_b256_250902_2047.pth'
    image_size: 224
    new_layers: []
  fg-clip:
    pretrained_weights_root_path: '/home/olivieri/exp/data/private/huggingface/hub/fg-clip'
    checkpoint_path: null

vle_name: 'flair'

seg:
  image_size: 520

mask_prs_path: '/home/olivieri/exp/data/private/prompts_data/by_model/LRASPP_MobileNet_V3/_mask_prs_'
