exp_name: "aug_1"
exp_desc: "Baseline training with slight augmentation (RandomCrop, RandomHzFlip(0.5)), fixed lr 1e-4."

tb_dir: "logs_tb"
log_dir: "logs"

seed: 42
device: "cuda"

log_every: 10

seg:
  image_size: 520
  train_decoder_only: False
  batch_size: 16
  num_epochs: 50
