exp_name: "2st_half"
exp_desc: "Test if we can split the training in two halfs and resetting the optimizer."

tb_dir: "logs_tb"
log_dir: "logs"

seed: 42
device: "cuda"

log_every: 10

seg:
  image_size: 520
  train_decoder_only: False
  batch_size: 16
  num_epochs: 45

vlm:
  image_size: 224
  alpha: 0.6
  sup_set_img_idxs: [16]
  temperature: 0.1
