exp_name: "baseline"
exp_desc: "baseline training with XEn and fixed lr, fixed center-cropping and no augmentations."

tb_dir: "logs_tb"
log_dir: "logs"

seed: 42
device: "cuda"

log_every: 10

seg:
  image_size: 520
  train_decoder_only: False
  batch_size: 16
  num_epochs: 50
