exp_name: "TEST"
exp_desc: ""

tb_dir: "logs_tb"
log_dir: "logs"

seed: 42
device: "cuda"

log_every: 10

segnet:
  image_size: 520
  train:
    train_decoder_only: False
    batch_size: 16
    num_epochs: 45

vle:
  image_size: 224
  train:
    batch_size: 16
    num_epochs: 32

vlm:
  image_size: 224
  alpha: 0.6
  sup_set_img_idxs: [16]
  temperature: 0.1

data_gen:
  root: "/home/olivieri/exp/data/data_gen/VOC2012"
  exp_name: "val_no_aug"
  batch_size: 16
  offset: 0 # img-text idx from which to start the generation
  alpha: 0.55 # the greater, the less scene is visible
