seed: 42
device: "cuda"

segnet:
  image_size: 520
  train:
    exp_name: "TEST"
    exp_desc: "" #  Optional
    train_decoder_only: False
    batch_size: 16
    num_epochs: 45
    log_dir_path: "/home/olivieri/exp/logs/segnet"
    tb_dir_path: "/home/olivieri/exp/logs_tb/segnet"
    log_every: 10

vle:
  image_size: 224
  train:
    exp_name: "TEST"
    exp_desc: "This is just a test" # Optional
    batch_size: 16
    num_epochs: 32
    mask_color: 'RB' # 'RB' (red-blue) or 'L' (black-white)
    log_dir_path: "/home/olivieri/exp/logs/vle"
    tb_dir_path: "/home/olivieri/exp/logs_tb/vle"
    log_every: 50

vlm:
  image_size: 224
  alpha: 0.6
  sup_set_img_idxs: [16]
  temperature: 0.1

data_gen:
  data_root: "/home/olivieri/exp/data/data_gen/VOC2012"
  exp_name: "train_3"
  batch_size: 1
  offset: 0 # img-text idx from which to start the generation
  alpha: 0.55 # the greater, the less scene is visible
  print_every: 100
