root_exp_path: '/home/olivieri/exp/data/private/exps/seg'
exp_name: '2-xen-rescale'
var_name: 'alpha10_b8'
exp_desc: "" # Optional

seg:
  pretrained_weights_path: '/home/olivieri/exp/data/private/exps/seg/2-xen-rescale/base/good_ckp_b8-251010_0642/weights/lraspp_mobilenet_v3_large-base-good_ckp_b8-251010_0642.pth'
  checkpoint_path: null
  image_size: 520
  train:
    train_decoder_only: False
    batch_size: 8
    num_epochs: 29
    precision: 'amp_bfloat16' # optional, should be ['amp' -> torch.float16, 'amp_bfloat16' -> torch.bfloat16]
    regularizers: ['dropout']
    lr_schedule:
      policy: 'cosine'
      base_lr: 1.0e-4
      warmup_length: 200 # 0 for no warmup
      epochs_cooldown: null
      lr_cooldown_power: null
      lr_cooldown_end: null
    grad_clip_norm: 10.0 # optional
    resume_path: '/home/olivieri/exp/data/private/exps/seg/2-xen-rescale/base/good_ckp_b8-251010_0642/weights/lraspp_mobilenet_v3_large-base-good_ckp_b8-251010_0642.pth' # optional (no resume)
    log_only_to_stdout: False
    log_every: 5
    with_text:
      with_text: True
      with_cache: True # is set to False if 'with_text' == False
      cache_path: '/home/olivieri/exp/data/private/exps/seg/2-xen-rescale/cache/cache_k=0'
      rescale_alpha: 10.0
      sign_classes_filter_k: 0
      cache_update_policy_percentile: 0.4

vle:
  pretrained_weights_root_path: '/home/olivieri/exp/data/private/torch_weights/vle/flair'
  checkpoint_path: '/home/olivieri/exp/data/private/exps/vle/1-dM_vs_dT/250902_2047/weights/flair-flair-cc3m-recap.pt-text_proj_L_b256_250902_2047.pth'
  image_size: 224
  new_layers: []

vlm:
  image_size: 224
  alpha: 0.6
  sup_set_img_idxs: [16]
  MLLMGenParams:
    temperature: 0.1
  batch_size: 1 # Optional, set to 1 if None

mask_prs_path: '/home/olivieri/exp/data/private/prompts_data/by_model/LRASPP_MobileNet_V3/_mask_prs_'
by_model: 'LRASPP_MobileNet_V3'
sup_set_gt_path: '/home/olivieri/exp/data/private/prompts_data/by_model/LRASPP_MobileNet_V3/class-splitted/sup_set_answer_gts.jsonl'
prompts_path: '/home/olivieri/exp/data/private/prompts_data/prompts'
